auto-tmux enhanced to keep things clean
- So it doesn't leave around stale env snapshots.
- Also fixed xtermtitle to not define bogus wrappers for commands aren't
  actually available.

diff --git a/plugin/auto-tmux b/plugin/auto-tmux
--- a/plugin/auto-tmux
+++ b/plugin/auto-tmux
@@ -19,6 +19,8 @@
 ################################################################################
 
 bash_plugin_login() {
+    # we can't do much if tmux is not available
+    type tmux &>/dev/null || return
     bash_default auto_tmux_env_root /tmp/auto-tmux.${SUDO_USER:-$LOGNAME}
     # a shorthand for enabling auto-tmux
     atmux() { auto_tmux_attach_at_login=true bash -l; }
@@ -45,17 +47,29 @@ bash_plugin_login() {
         done >"$auto_tmux_link" 2>/dev/null
         chmod a-w "$auto_tmux_link"
     }
-    if ! type tmux &>/dev/null; then
-        # we can't do much if tmux is not available
-        if ! $bash_autoload; then
-            echo "auto-tmux: not found from PATH" >&2
-        fi
-        unset atmux
-    elif [ -z "$TMUX" -a -z "$SSH_CONNECTION" -a -z "$auto_tmux_attach_at_login" ]; then
+    -atmux-all() {
+        # all connections
+        (cd "$auto_tmux_env_root" && \ls -t) 2>/dev/null
+    }
+    -atmux-alive() {
+        # live connections
+        (cd "$auto_tmux_env_root" &&
+        \ls -t $(ps -o pid= -p `-atmux-all`)) 2>/dev/null
+    }
+    -atmux-cleanup() {
+        # remove stale connections
+        local patt= pid=
+        for pid in $(-atmux-alive); do patt+="${patt:+\\|}$pid"; done
+        local stalePids=$(-atmux-all | grep -v "^\\($patt\\)$")
+        (cd "$auto_tmux_env_root" && rm -f $stalePids)
+        # remove stale links
+        find -L "$auto_tmux_env_root" -type l -exec rm -f {} \;
+    }
+    if [ -z "$TMUX" -a -z "$SSH_CONNECTION" -a -z "$auto_tmux_attach_at_login" ]; then
         # local shell, but auto-tmux wasn't explicitly configured
         # skip attaching to the tmux session
         unset -v auto_tmux_env_root
-        unset -f atmux-{reset,save}
+        unset -f atmux-{reset,save} -atmux-{all,alive,cleanup}
     elif [ -n "$TMUX" ]; then
         # working inside tmux, prepare stuffs
         auto_tmux_link="$auto_tmux_env_root/.$$"
@@ -63,15 +77,6 @@ bash_plugin_login() {
         unset atmux
         
         # set useful tmux related commands
-        -atmux-all() {
-            # all connections
-            (cd "$auto_tmux_env_root" && \ls -t) 2>/dev/null
-        }
-        -atmux-alive() {
-            # live connections
-            (cd "$auto_tmux_env_root" &&
-            \ls -t $(ps -o pid= -p `-atmux-all`)) 2>/dev/null
-        }
         -atmux-current() {
             # current connection
             readlink "$auto_tmux_link"
@@ -124,15 +129,6 @@ bash_plugin_login() {
                 (cd "$auto_tmux_env_root" && rm -f $pids)
             fi 2>/dev/null
         }
-        -atmux-cleanup() {
-            # remove stale connections
-            local patt= pid=
-            for pid in $(-atmux-alive); do patt+="${patt:+\\|}$pid"; done
-            local stalePids=$(-atmux-all | grep -v "^\\($patt\\)$")
-            (cd "$auto_tmux_env_root" && rm -f $stalePids)
-            # remove stale links
-            find -L "$auto_tmux_env_root" -type l -exec rm -f {} \;
-        }
 
         atmux-record-windows() {
             local f=${1:-~/.tmux.windows}
@@ -166,6 +162,8 @@ bash_plugin_login() {
             mkdir -p "$auto_tmux_env_root"
             chmod a=,u=rwx "$auto_tmux_env_root"
         fi
+        # clean up stale environment snapshots first
+        -atmux-cleanup
         local conn=$$
         local auto_tmux_env="$auto_tmux_env_root/$conn"
         rm -f "$auto_tmux_env"
